# Generated by Django 3.1.1 on 2021-04-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Island', 'Andaman & Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'ArunachalPradesh'), ('Asam', 'Asam'), ('Bihar', 'Bihar'), ('Chandhighar', 'Chandhighar'), ('Chattisghar', 'Chattisghar'), ('Dadar & Nagar Haveli', 'Dadar & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Gujarath', 'Gujarath'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himichal Pradesh'), ('Keraka', 'Kerala'), ('Madhyapradesh', 'Madhyapradesh'), ('Maharashtra', 'Maharashtra')], max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('m', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Ware'), ('BW', 'Bottom Ware')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product_image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'Onthe way'), ('Deivered', 'Delivered'), ('Cancle', 'Cancle')], default='Pending', max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
