# Generated by Django 3.2.12 on 2022-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('None', 'Select State'), ('Andaman & Nicobar Island', 'Andaman & Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'ArunachalPradesh'), ('Asam', 'Asam'), ('Bihar', 'Bihar'), ('Chandhighar', 'Chandhighar'), ('Chattisghar', 'Chattisghar'), ('Dadar & Nagar Haveli', 'Dadar & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Goa', 'Goa'), ('Gujarath', 'Gujarath'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himichal Pradesh'), ('Keraka', 'Kerala'), ('Madhyapradesh', 'Madhyapradesh'), ('Maharashtra', 'Maharashtra')], max_length=150),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('None', 'Select status'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'Onthe way'), ('Deivered', 'Delivered'), ('Cancle', 'Cancle')], default='Pending', max_length=150),
        ),
    ]
