# Generated by Django 3.2.12 on 2022-03-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220302_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.BigIntegerField()),
            ],
        ),
    ]
